apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.db.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.db.DB_PASSWORD | quote }}

  POSTGRES_USER: {{ .Values.db.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.POSTGRES_PASSWORD | quote }}

  PGADMIN_DEFAULT_EMAIL: {{ .Values.db.PGADMIN_DEFAULT_EMAIL | quote }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.db.PGADMIN_DEFAULT_PASSWORD | quote }}
