apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-monitoring-platform
type: Opaque
stringData:
  DB_USER: "root"
  DB_PASSWORD: "root"

  POSTGRES_USER: "root"
  POSTGRES_PASSWORD: "root"

  PGADMIN_DEFAULT_EMAIL: "root@gmail.com"
  PGADMIN_DEFAULT_PASSWORD: "root"
  PGADMIN_PORT: "5050"